environment:
  matrix:
    - nodejs_version: '12'
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn
test_script:
  - yarn test
build: off
before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb database_test
  - psql -c "ALTER USER postgres WITH PASSWORD 'ytreza321';" -U postgres 
 
services:
  - postgresql101
