environment:
  matrix:
    - nodejs_version: '12'
install:
  - yarn
test_script:
  - yarn test
build: off
before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=ytreza321
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb database_test
services:
  - postgresql101
